# Generated by Django 5.1.4 on 2025-11-06 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, help_text='Second product image (optional)', null=True, upload_to='products/images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, help_text='Third product image (optional)', null=True, upload_to='products/images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='products/images/default.png', help_text='Main product image (required)', null=True, upload_to='products/images/'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
